version: '3.7'
services:
  redis:
    image: bitnami/redis:7.2
    restart: always
    volumes:
      - redis-data:/bitnami/redis/data
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-secret}
      REDIS_PORT_NUMBER: 6379
    networks:
      - net

  elastic:
    image: elasticsearch:7.17.9
    restart: always
    volumes:
      - elastic-data:/elasticsearch/data
    ports:
      - '9201:9200'
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      "discovery.type": "single-node"
      "xpack.security.enabled": "false"
      "bootstrap.system_call_filter": "false"
      "ingest.geoip.downloader.enabled": "false"
      "http.host": "0.0.0.0"
      "transport.host": "127.0.0.1"
    networks:
      - net

  app:
    image: demorfi/synox-web:latest
    restart: always
    volumes:
      - storage:/synox-web/storage
      - files:/synox-web/public/files
    ports:
      - '8002:80'
      - '2346:2346'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-secret}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTIC_HOST: elastic:9200
    networks:
      - net
    depends_on:
      - redis
      - elastic

volumes:
  redis-data:
  elastic-data:
  storage:
  files:

networks:
  net:
    driver: bridge