version: '3.7'
services:
  app:
    image: demorfi/synox-web:latest
    restart: always
    volumes:
      - storage:/synox-web/storage
      - files:/synox-web/public/files
    ports:
      - '8002:80'
      - '2346:2346'
    environment:
      APP_MODE: ${APP_MODE:-prod}
      CACHE_EXPIRE: ${CACHE_EXPIRE:-86400}
      WORKER_BROADCAST_HOST: ${WORKER_BROADCAST_HOST:-0.0.0.0}
      WORKER_BROADCAST_PORT: 2346
      WORKER_USE_SSL: ${WORKER_USE_SSL:-false}
      WORKER_SSL_CERT_PATH: ${WORKER_SSL_CERT_PATH:-null}
      WORKER_SSL_KEY_PATH: ${WORKER_SSL_KEY_PATH:-null}
    networks:
      - net

volumes:
  storage:
  files:

networks:
  net:
    driver: bridge