#!/bin/sh

##########################################################################
# Synox make hosting file.                                               #
#                                                                        #
# @author  demorfi <demorfi@gmail.com>                                   #
# @version 1.0                                                           #
# @source https://github.com/demorfi/synox                               #
# @license http://opensource.org/licenses/MIT Licensed under MIT License #
##########################################################################

DIR_PATH=$(dirname $(readlink -f "$0"))
BUILD_DIR=build
SOURCE="INFO SynoFileHostingSynox.php"
PKG_NAME="synox.host"
PACKAGE=${DIR_PATH##*/}

clean()
{
    if [ -d $BUILD_DIR ]; then
        echo "del $BUILD_DIR"
        rm -rf $BUILD_DIR
    fi

    if [ -f $PKG_NAME ]; then
        echo "del $PKG_NAME"
        rm -f $PKG_NAME
    fi
}

build()
{
    if [ ! -d $BUILD_DIR ]; then
        mkdir -p $BUILD_DIR
    fi

    USED_HOST=$(cat INFO | grep \"host\" | sed '/"host": */!d; s///;q;' | sed 's/ //g')
    echo -n "Use host $PKG_NAME (default: $USED_HOST):" ; read USE_HOST

    if [ $USE_HOST ] && [ "$USE_HOST" != "$USED_HOST" ]; then
        INFO=$(cat INFO)
        OLD_HOST=$(cat INFO | grep \"host\")
        NEW_HOST=${OLD_HOST//$USED_HOST/\"$USE_HOST\"}
        echo "${INFO/$OLD_HOST/$NEW_HOST}" > INFO
    fi

    cp $SOURCE $BUILD_DIR
    (cd $BUILD_DIR ; tar -czf ../$PKG_NAME *)
}

if [ ! $1 ]; then
    build
    exit 0
fi

if [ $1 ] && [ $1 = "clean" ]; then
    clean
    exit 0
fi

exit 0
