#!/bin/sh

##########################################################################
# Synox make hosting file.                                               #
#                                                                        #
# @author  demorfi <demorfi@gmail.com>                                   #
# @version 2.0                                                           #
# @source https://github.com/demorfi/synox                               #
# @license https://opensource.org/license/mit/                           #
##########################################################################

DIR_PATH=$(dirname $(readlink -f "$0"))
BUILD_DIR=build
SOURCE="INFO SynoFileHostingSynox.php"
PKG_NAME="synox.host"
PACKAGE=${DIR_PATH##*/}

clean()
{
  if [ -d $BUILD_DIR ]; then
    echo "del $BUILD_DIR"
    rm -rf $BUILD_DIR
  fi

  if [ -f $PKG_NAME ]; then
    echo "del $PKG_NAME"
    rm -f $PKG_NAME
  fi
}

build()
{
  if [ ! -d $BUILD_DIR ]; then
    mkdir -p $BUILD_DIR
  fi

  cp $SOURCE $BUILD_DIR
  (cd $BUILD_DIR ; tar -czf ../$PKG_NAME *)
}

if [ ! $1 ]; then
  build
  exit 0
fi

if [ $1 ] && [ $1 = "clean" ]; then
  clean
  exit 0
fi

exit 0
